Updated .NET SDK to 7.0
nunit/docfx-action pull request #32
Opened 2023-08-20 09:15 UTC by AptiviCEO

This pull request will allow docfx-action to use the .NET 7.0 SDK to be able to build applications that are built with .NET 7.0.

Tested with Nitrocid KS and got the following results:

- [API Documentation](https://aptivi.github.io/NitrocidKS/api/KS.Arguments.ArgumentBase.html)
- [Job log](https://github.com/Aptivi/NitrocidKS/actions/runs/5916515008/job/16043880598)

Thanks!

2023-08-20 09:16 UTC, AptiviCEO commented
@microsoft-github-policy-service agree

2023-09-11 15:48 UTC, AptiviCEO commented
@microsoft-github-policy-service agree

2023-09-11 15:56 UTC, AptiviCEO commented
@microsoft-github-policy-service agree

2023-09-22 15:35 UTC, bfren commented
This would be super handy if it could be merged into a release soon?

2023-09-26 16:38 UTC, AptiviCEO commented
@dotnet-policy-service agree

2023-10-14 19:44 UTC, SeanKilleen commented
Sorry @AptiviCEO / @bfren! Thanks for your patience. My brother got married and I think I totally missed this PR at the time. I'll get it merged in.

2023-10-14 19:48 UTC, SeanKilleen requested changes
One minor change and then should be good.

2023-10-14 19:48 UTC, SeanKilleen commented on Dockerfile
> +RUN dotnet tool install --global docfx --version 2.70.4
```suggestion
RUN dotnet tool install --global docfx --version 2.71.0
```

Please update to 2.71.0, or merge main into this branch. We're at 2.71.0 on our main branch.

I'd do it myself but wasn't given permission to edit this PR branch.

2023-10-14 20:03 UTC, SeanKilleen approved these changes
Thanks!

2023-10-14 20:04 UTC, merged

2023-10-14 20:07 UTC, AptiviCEO commented
You are welcome, and thanks for approving the changes @SeanKilleen. I'll tell you when .NET 8 releases.

2023-10-14 20:31 UTC, SeanKilleen commented
Oh I'm clued into the release date. :)